### ISSUE TITLE
ALLOW and SKIP buttons not working

### ISSUE THREAD

**Issue by Clyfton** [wokhansoft/WFN#2]
Reference version 2 beta 2
I set the firewall to block and alert on all outgoing connections.
I used the SKIP PROGRAM function and continue to see prompts from same program.
The program was for APC UPS monitoring (Powerchute Business Edition Server).
Same for Host Process for Windows Services.
I stopped using WFN at that point because repeated prompts for same program is the problem I've had since the start.
I thought when I clicked ALLOW that I was adding a rule for the alerting program. I see lots of allowed programs in the Firewall Rules, so the ALLOW button doesn't seem to work either.

**Comment by AtlasHackert** [comment]
I assume you mean version 2 beta 1?

"Skip program" only skips current notifications; the skip-button (in V2 anyway) was never meant to permanently ignore connection attempt. In fact, if that's what you want, just create a block-rule: it's effectively the same: the connection gets blocked, and you don't get a notification.
Multiple prompts: are they really duplicates, or are they for different ports/IPs? Can you check the existing rules / check the options in the Advanced panel of the Notifier to see if they really are identical?

**Comment by Clyfton** [comment]
I do not want to block.  As I mentioned above, I want to allow.  That has been my problem with every version, repeated prompts for a program I have already allowed.

**Comment by AtlasHackert** [comment]
Can you check whether the rules are indeed identical, or if port numbers/IP addresses have changed? And post screenshots of the rules?
Can you please post a screenshot of the Notifier with the Advanced panel expanded of one of the connections that should have been allowed by the rules?

**Comment by Clyfton** [comment]
It doesn't matter what the port numbers and IP addresses are ... when I click ALLOW then I am saying that I trust the program and that I don't want to see any more notifications ever again from that program regardless of port or IP.  That is standard firewall Ops.  And yes, the ports and IPs are different.  I don't know what you mean by the advanced panel expanded.

**Comment by AtlasHackert** [comment]
> It doesn't matter what the port numbers and IP addresses are ... when I click ALLOW then I am saying that I trust the program and that I don't want to see any more notifications ever again from that program regardless of port or IP.

It depends on your viewpoint. Are you allowing the program, or the connection? I've got several programs where I allow certain ports, but not others... But it should be made more clear, I agree. I'll see what I can do about that.

You can customize the rules WFN creates by expanding that Advanced panel in the Notifier, and changing the options. The Advanced panel is the button at the bottom of the Notifier: https://camo.githubusercontent.com/b50db23cde74aef5bbc76661b0327be63bf2cc98/687474703a2f2f776f6b68616e2e6f6e6c696e652e66722f70726f67732f77666e2f6e6f7469666965722e504e47

**Comment by Clyfton** [comment]
Yeah ... I kinda figured as I was typing my last rant that you guys were thinking CONNECTIONS and I was thinking PROGRAMS.  You guys are way more nerdy than me (that's a compliment).  I am not nerdy enough to think about the port and connection level.  I just want to be able to trust programs so I don't get nagged by continuous prompts.  Maybe you need an ALLOW CONNECTION and an ALLOW PROGRAM button.  When you get the ALLOW PROGRAM button, I'll give it a try again :)

**Comment by ahubbard** [comment]
Great work!  I've been tracking your progress and donating periodically. I have the same issue and I'm using the advanced panel correctly.  Screenshot attached 
![image](https://cloud.githubusercontent.com/assets/3825627/26565069/e6d698a8-44b5-11e7-97af-2c8f3d2d9fe3.png) and it happens with all my rules 
![image](https://cloud.githubusercontent.com/assets/3825627/26565081/032742aa-44b6-11e7-930a-00f294909cd2.png) I noticed the title bar says "WFN v2.0 ALPHA" but I confirmed I'm using the lastest beta with map db.

**Comment by AtlasHackert** [comment]
> Maybe you need an ALLOW CONNECTION and an ALLOW PROGRAM button.
Yes, that is a good idea! I'll get working on that ASAP.

@ahubbard: The "Office Click to Run" files may not be identical; check the paths. Every different version installs in a different path, leading to many similar but not identical rules.
VNC Server: I'll check that out.

**Comment by AtlasHackert** [comment]
Figured out the problem of the VNC Server. It's one of these programs that's running a service, but starting connections outside of it. As a workaround: in the Advanced-panel, disable the checkbox for the "Service", and then create the rule.

**Comment by ahubbard** [comment]
Great for VNC.  I've got several of these duplicates though :)
![image](https://cloud.githubusercontent.com/assets/3825627/26611876/29e9fad0-457f-11e7-975e-019c6113c195.png)
![image](https://cloud.githubusercontent.com/assets/3825627/26611891/3935ae12-457f-11e7-99a2-10654683a8cc.png)
![image](https://cloud.githubusercontent.com/assets/3825627/26611905/52082384-457f-11e7-8238-aba75179a119.png)

**Comment by AtlasHackert** [comment]
@ahubbard: I've released a new version, 2.0 Beta 2. Can you try that one for these programs? You should remove all those rules manually before, just to make sure they don't interfere.

@Clyfton: I haven't made separate buttons for connection vs program yet, but I've cleaned up the code around it, so it should now be easy to implement. Next release, hopefully!

**Comment by ahubbard** [comment]
Anectodately, I seem to be receiving less alerts overall. Looks like the new beta took care of VNC, no further alerts there.  But the issue still remains for other services unfortunately:
![image](https://cloud.githubusercontent.com/assets/3825627/26756116/ba86b9b0-4869-11e7-9417-b3de6fa5942a.png)
and for non-services:
![image](https://cloud.githubusercontent.com/assets/3825627/26756137/21e46b0c-486a-11e7-9f71-1c655d75e7c9.png)

**Comment by wokhan** [comment]
Became a duplicate of #29 (sort of), for the "allow program" part. Closing this issue as it is already in our backlog.
